name: Test PyPI Installation

on:
  workflow_dispatch:

  push:
    branches: [ master, dev/jan ]
  pull_request:
    branches: [ master, dev/jan ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
    - name: Install from PyPI
      run: |
        pip install mdp-playground[extras]
    - name: Basic functionality test
      run: |
        run-mdpp-experiments --help
